CREATE TABLE videos (
    id VARCHAR NOT NULL PRIMARY KEY,
    uploader VARCHAR NOT NULL CONSTRAINT videos_users_id_fk REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
    title VARCHAR NOT NULL,
    description TEXT NOT NULL,
    video_path VARCHAR NOT NULL,
    thumbnail_path VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc')
);
