CREATE TABLE comments (
	id VARCHAR CONSTRAINT comments_pk PRIMARY KEY,
	video_id VARCHAR NOT NULL CONSTRAINT comments_videos_id_fk REFERENCES videos ON UPDATE CASCADE ON DELETE CASCADE,
	user_id VARCHAR NOT NULL CONSTRAINT comments_users_id_fk REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
	content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc')
);

