CREATE TABLE creators (
	user_id VARCHAR CONSTRAINT creators_pk PRIMARY KEY CONSTRAINT creators_users_id_fk REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE followers (
	creator_id VARCHAR NOT NULL CONSTRAINT followers_creators_id_fk REFERENCES creators ON UPDATE CASCADE ON DELETE CASCADE,
	viewer_id VARCHAR NOT NULL CONSTRAINT followers_users_id_fk REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'),
    PRIMARY KEY (creator_id, viewer_id)
);
